[package]
name = "hello_me"
version = "0.1.0"
edition = "2024"

[dependencies]
my_library = { git = "https://github.com/Greenfire44Official/my_library.git" }

[[bin]]
name = "hello"
path = "src/main.rs"